# Generated by Django 4.2.7 on 2025-09-17 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '登録試行',
                'verbose_name_plural': '登録試行',
                'db_table': 'auth_registration_attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='auth_regist_ip_addr_231024_idx'), models.Index(fields=['username', 'timestamp'], name='auth_regist_usernam_01b0b6_idx'), models.Index(fields=['email', 'timestamp'], name='auth_regist_email_f60b7a_idx')],
            },
        ),
    ]
